# -*- coding: utf-8 -*-
"""DiabetesPredictionML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4s3Ga_zBV-b6Io2bstql7-pv8wZYfHX

Work flow

1. Diabetes Data
2. Data pre-processing  
3. Train Test Split ( Accuracy Score)
4. SVM Model ( Support Vecotr Machine Clasifier)
5. Run model with Test Data to see if it works
"""

import numpy as np # used to make numpy arrays
import pandas as pd # helps organize data in tables
from sklearn.preprocessing import StandardScaler # use this library to standardize the data into a standard common range
from sklearn.model_selection import train_test_split # helps for data splitting
from sklearn import svm
from sklearn.metrics import accuracy_score

"""Data Collection & Analysis

PIMA Diabetes Dataset
"""

# loading the diabetes dataset to a pandas DF
diabetes_dataset = pd.read_csv('/content/diabetes.csv')
diabetes_dataset.head()

# number of rows and columns in this dataset
# (x,y): x = number of patients, y = number of parameters
diabetes_dataset.shape

#getting statistical measure of the data
diabetes_dataset.describe()

# this will tell us how many counts of each value there is for each of the outcomes
diabetes_dataset['Outcome'].value_counts()
# 0 = Non Diabetic, 1 = Diabetic

# this is giving the average statistics for those that are diabetic vs non diabetic
diabetes_dataset.groupby('Outcome').mean()

"""Splitting the Data with labels"""

X = diabetes_dataset.drop(columns = 'Outcome', axis = 1)
Y = diabetes_dataset['Outcome']

print(X)

print(Y)

"""Data Standardization (keeping the data all in a certain range)"""

scaler = StandardScaler()

scaler.fit(X)

standardized_data = scaler.transform(X)

print(standardized_data)

X = standardized_data
Y = diabetes_dataset['Outcome']

print(X)
print(Y)

"""Train Test Split
* here we are splitting the X & Y data into a training set and a testing set

* X & Y are the data we want to split

* test_size = 0.2 means we want to save 20% of the data to be for testing and the remaining 80% for training

* stratify = Y; to prevent bias and make a similar proportion of data on each set of data between test and train

* random_state = 2- sets a seed for the random number generator so that the data splits into the exact same training and testing sets every single time you run the code.

"""

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size =  0.2, stratify = Y, random_state = 2)

print(X.shape, X_train.shape, X_test.shape)

"""Training the model"""

classifier = svm.SVC(kernel = 'linear')

# Training the support vector machine classifier
classifier.fit(X_train, Y_train)

"""Model Evaluation"""

#Accuracy Score  on the training data

X_train_predicition = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_predicition, Y_train)

print('Accuracy Score of the training data:', training_data_accuracy)

#Accuracy Score  on the test data

X_test_predicition = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_predicition, Y_test)

print('Accuracy Score of the test data:', test_data_accuracy)

# the outcome here is that the test data = 77.2% and the train data = 78.6%,
#shows that the training is not over trained. if the training > test by a lot it  signifies overfitting

"""Making a predictive System"""

input_data = (4,110,92,0,0,37.6,0.191,30)

#change input_data to a numpy array
input_data_as_numpy_array = np.asanyarray(input_data)

# reshape the array a we are prediciting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standarize the input_data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')